pipeline{

    agent any

    stages{

        stage('Git Checkout'){

            steps{

                script{

                    gitcheckout(
                        branch: "main"
                        url: "https://github.com/mtosin123/tars-new-java.git"

                    )


                }
            }
        }
    }
}